/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Health check endpoint */
    get: operations['getHealth'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/users/{userId}/audio/upload': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Create audio upload for user */
    post: operations['createUserAudioUpload'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/users/{userId}/audio': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List user's audio files */
    get: operations['listUserAudio'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/users/{userId}/audio/{audioId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get user's audio file details and download URL */
    get: operations['getUserAudio'];
    put?: never;
    post?: never;
    /** Delete user's audio file */
    delete: operations['deleteUserAudio'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/users/{userId}/audio/{audioId}/process': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Start processing user's audio file */
    post: operations['processUserAudio'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/users': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get all users (admin only) */
    get: operations['getAllUsers'];
    put?: never;
    /** Create user profile from JWT claims */
    post: operations['createUserProfile'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/users/{userId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get user by ID */
    get: operations['getUserById'];
    /** Update user profile */
    put: operations['updateUser'];
    post?: never;
    /** Delete user profile (local only) */
    delete: operations['deleteUserProfile'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/users/{userId}/change-password': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Change user password */
    post: operations['changePassword'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/users/{userId}/account': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Delete user account (Cognito + local profile) */
    delete: operations['deleteUserAccount'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/users/signup': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Sign up new user (public endpoint) */
    post: operations['signUpUser'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/users/confirm': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Confirm user sign up (public endpoint) */
    post: operations['confirmSignUp'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    ErrorResponse: {
      /** @description Error message */
      error: string;
      /** @description Detailed error message */
      message?: string;
    };
    MessageResponse: {
      /** @description Success message */
      message: string;
    };
    HealthResponse: {
      /** @enum {string} */
      status: 'healthy';
      /** @example english-learning-app-backend */
      service: string;
      /** @example 1.2.1 */
      version: string;
    };
    CreateAudioRequest: {
      /**
       * @description Name of the audio file
       * @example my-audio.mp3
       */
      fileName: string;
      /**
       * @description MIME type of the audio file
       * @example audio/mpeg
       * @enum {string}
       */
      contentType:
        | 'audio/mpeg'
        | 'audio/mp3'
        | 'audio/mp4'
        | 'audio/m4a'
        | 'audio/wav'
        | 'audio/wave'
        | 'audio/x-wav'
        | 'audio/webm'
        | 'audio/ogg'
        | 'audio/flac'
        | 'audio/aac';
      /**
       * @description Duration in seconds (optional)
       * @example 30
       */
      duration?: number;
      /**
       * @description File size in bytes (optional)
       * @example 1048576
       */
      fileSize?: number;
    };
    CreateAudioResponse: {
      /** @example true */
      success: boolean;
      /**
       * Format: uuid
       * @description Unique identifier for the audio file
       * @example 550e8400-e29b-41d4-a716-446655440000
       */
      audioId: string;
      /**
       * Format: uri
       * @description Presigned URL for uploading the file
       */
      uploadUrl: string;
      /**
       * @description URL expiration time in seconds
       * @example 3600
       */
      expiresIn: number;
    };
    AudioFile: {
      /**
       * Format: uuid
       * @description Audio file UUID
       */
      id: string;
      /** @description Original file name */
      fileName: string;
      /** @description MIME type of the audio file */
      contentType: string;
      /** @description File size in bytes */
      fileSize: number;
      /** @description Duration in seconds (optional) */
      duration?: number;
      /**
       * @description Processing status
       * @enum {string}
       */
      status: 'UPLOADED' | 'PROCESSING' | 'PROCESSED' | 'FAILED';
      /**
       * Format: date-time
       * @description Upload timestamp
       */
      uploadedAt: string;
      /**
       * Format: date-time
       * @description Processing completion timestamp (optional)
       */
      processedAt?: string;
      /**
       * Format: uuid
       * @description Transcription job ID (optional)
       */
      transcriptionId?: string;
      /** @description Error message if processing failed (optional) */
      processingError?: string;
    };
    ListAudioResponse: {
      /** @example true */
      success: boolean;
      /** @description List of audio files */
      audioFiles: components['schemas']['AudioFile'][];
      /** @description Pagination token for next page (optional) */
      lastEvaluatedKey?: string;
      /**
       * @description Total number of audio files for the user
       * @example 42
       */
      totalCount: number;
    };
    GetAudioResponse: {
      /** @example true */
      success: boolean;
      audio: components['schemas']['AudioFile'];
      /**
       * Format: uri
       * @description Presigned URL for downloading the file
       */
      downloadUrl: string;
      /**
       * @description URL expiration time in seconds
       * @example 3600
       */
      expiresIn: number;
    };
    DeleteAudioResponse: {
      /** @example true */
      success: boolean;
      /** @example Audio file deleted successfully */
      message: string;
    };
    ProcessAudioResponse: {
      /** @example true */
      success: boolean;
      /** @example Audio processing started successfully */
      message: string;
      /**
       * Format: uuid
       * @description Unique identifier for the transcription job
       */
      transcriptionId: string;
      /**
       * @description New processing status
       * @enum {string}
       */
      status: 'PROCESSING';
    };
    CreateUserRequest: {
      /**
       * Format: email
       * @description User email (optional, extracted from JWT if not provided)
       */
      email?: string;
      /** @description User display name (optional, extracted from JWT if not provided) */
      name?: string;
    };
    UserResponse: {
      /**
       * Format: uuid
       * @description User UUID from Cognito
       */
      id: string;
      /**
       * Format: email
       * @description User email address
       */
      email: string;
      /** @description User display name */
      name: string;
      /**
       * Format: date-time
       * @description Profile creation timestamp
       */
      createdAt: string;
      /**
       * Format: date-time
       * @description Profile last update timestamp
       */
      updatedAt: string;
    };
    UpdateUserRequest: {
      /** @description Updated display name */
      name?: string;
      /**
       * Format: email
       * @description Updated email address (must match Cognito)
       */
      email?: string;
    };
    ChangePasswordRequest: {
      /** @description Current password */
      oldPassword: string;
      /** @description New password */
      newPassword: string;
    };
    SignUpRequest: {
      /**
       * Format: email
       * @description User email address
       */
      email: string;
      /** @description User password */
      password: string;
      /** @description User display name (optional) */
      name?: string;
    };
    SignUpResponse: {
      /** @example User signed up successfully. Please check your email for verification code. */
      message: string;
      /** @description Cognito user UUID */
      userSub: string;
      codeDeliveryDetails?: {
        /** @example email */
        attributeName?: string;
        /** @example EMAIL */
        deliveryMedium?: string;
        /** @example t***@example.com */
        destination?: string;
      };
    };
    ConfirmSignUpRequest: {
      /**
       * Format: email
       * @description User email address
       */
      email: string;
      /** @description Verification code sent to email */
      confirmationCode: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  getHealth: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Service health status */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HealthResponse'];
        };
      };
    };
  };
  createUserAudioUpload: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description User UUID */
        userId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateAudioRequest'];
      };
    };
    responses: {
      /** @description Audio upload created successfully */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CreateAudioResponse'];
        };
      };
      /** @description Bad request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Forbidden - cannot access another user's resources */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  listUserAudio: {
    parameters: {
      query?: {
        /** @description Maximum number of items to return */
        limit?: number;
        /** @description Pagination token for next page */
        lastEvaluatedKey?: string;
        /** @description Filter by audio status */
        status?: 'UPLOADED' | 'PROCESSING' | 'PROCESSED' | 'FAILED';
      };
      header?: never;
      path: {
        /** @description User UUID */
        userId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Audio files retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ListAudioResponse'];
        };
      };
      /** @description Bad request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Forbidden - cannot access another user's resources */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  getUserAudio: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description User UUID */
        userId: string;
        /** @description Audio UUID */
        audioId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Audio details retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['GetAudioResponse'];
        };
      };
      /** @description Bad request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Forbidden - cannot access another user's resources */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Audio file not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  deleteUserAudio: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description User UUID */
        userId: string;
        /** @description Audio UUID */
        audioId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Audio file deleted successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DeleteAudioResponse'];
        };
      };
      /** @description Bad request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Forbidden - cannot access another user's resources */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Audio file not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  processUserAudio: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description User UUID */
        userId: string;
        /** @description Audio UUID */
        audioId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Audio processing started successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProcessAudioResponse'];
        };
      };
      /** @description Bad request or audio not in processable state */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Forbidden - cannot access another user's resources */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Audio file not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  getAllUsers: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description List of users retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserResponse'][];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  createUserProfile: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        'application/json': components['schemas']['CreateUserRequest'];
      };
    };
    responses: {
      /** @description User profile created successfully */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserResponse'];
        };
      };
      /** @description Bad request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description User already exists */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  getUserById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description User UUID */
        userId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description User retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserResponse'];
        };
      };
      /** @description Bad request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Forbidden - can only access own profile */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description User not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  updateUser: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description User UUID */
        userId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateUserRequest'];
      };
    };
    responses: {
      /** @description User updated successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserResponse'];
        };
      };
      /** @description Bad request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Forbidden - can only update own profile */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description User not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  deleteUserProfile: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description User UUID */
        userId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description User profile deleted successfully */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Bad request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Forbidden - can only delete own profile */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description User not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  changePassword: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description User UUID */
        userId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ChangePasswordRequest'];
      };
    };
    responses: {
      /** @description Password changed successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['MessageResponse'];
        };
      };
      /** @description Bad request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Unauthorized or invalid current password */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Forbidden - can only change own password */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  deleteUserAccount: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description User UUID */
        userId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Account deleted successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['MessageResponse'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Forbidden - can only delete own account */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Failed to delete account */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  signUpUser: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SignUpRequest'];
      };
    };
    responses: {
      /** @description User signed up successfully */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SignUpResponse'];
        };
      };
      /** @description Bad request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description User already exists */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  confirmSignUp: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ConfirmSignUpRequest'];
      };
    };
    responses: {
      /** @description Email verified successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['MessageResponse'];
        };
      };
      /** @description Bad request or invalid confirmation code */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
}
